services:
  backend:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - portfolio-app:/app
    networks:
      - backend_network

networks:
  backend_network:


volumes:
  portfolio-app:
